### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by Karthic-Hackintosh** [abiosoft/caddy-git#1]
I want to use [Sourcegraph](https://sourcegraph.com) for caddy-git code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/abiosoft/caddy-git. (It should only take 30 seconds.)

Thank you!

**Comment by abiosoft** [comment]
It is available on Sourcegraph now. Thanks.
