### ISSUE TITLE
Problem with executing go command 

### ISSUE THREAD

**Issue by pavlik** [abiosoft/caddy-git#13]
I detect problems in `git add-on`.
When I run the `go` command, git-addon can not see it. Despite GOPATH & GOROOT registered in the global profile and in the profile of the current user (root). Caddy-server is started using `supervisord` user = root.

If I write the absolute path to `go`, then the command is executed, but the execution stage climbs the error that the program does not see the packages used in the program, although they are installed in the system.  If I run `go install` manualy in the program folder, then the command exec without errors.

**Comment by abiosoft** [comment]
This is not an issue with git add-on. It is an issue with the session supervisord is using to execute caddy.

Can you manually set the environment variables with supervisord ?

**Comment by pavlik** [comment]
@abiosoft If I set env vars in supervisord config - all works normal.

**Comment by abiosoft** [comment]
Good to hear that. 

Thanks.
