### ISSUE TITLE
Need new future: long running commands

### ISSUE THREAD

**Issue by pavlik** [abiosoft/caddy-git#14]
It would be cool if it will be possible that `git add-on` perform multiple commands and run long-running commands, then we will abandon `supervisord`.

**Comment by abiosoft** [comment]
I've started working on this. :)

However, this is gonna be basic and will definitely not be as feature-rich as `supervisord`.

**Comment by abiosoft** [comment]
This is now supported. You can use `then_long` config for this. Check README.

**Comment by pavlik** [comment]
Thank you very much! Immediately begin testing

**Comment by pavlik** [comment]
@abiosoft Can `then_long` check if service is down & restart it?

**Comment by abiosoft** [comment]
I did not cater for shutdown but now that you've mentioned it, I see the need. What I am gonna make it do is to check the exit status. If it exits on error then it is gonna be restarted.

You can use https://github.com/caddyserver/caddyext for that.

Thanks.

**Comment by pavlik** [comment]
@abiosoft thanks twice :)

**Comment by abiosoft** [comment]
Done :)

**Comment by pavlik** [comment]
Where I can see log file of `then_long` command?

**Comment by abiosoft** [comment]
It logs to wherever caddy outputs to.

I'd advise you pull latest changes. I made two minor bug fixes last night.

Cheers :)

**Comment by pavlik** [comment]
pull just now :) :+1:

**Comment by pavlik** [comment]
I have an error: `Parse error: Wrong argument count or unexpected line ending after 'then_long'`
I try to quote command `mimozaflowers`, but this not help.

This is my Caddyfile
```
mimozaflowers.ru, www.mimozaflowers.ru {
        root /root/gocode/src/github.com/pavlik/mimozaflowers
        gzip
        log /var/log/mimoza_access.log

        errors {
                log /var/log/mimoza_error.log
                #404 404.html # Not Found
        }

        git {
                path ./
                repo https://github.com/pavlik/mimozaflowers
                hook /webhook my_secret
                then go install
                then_long /root/gocode/bin/mimozaflowers
        }

        proxy / localhost:9000
}
```

**Comment by abiosoft** [comment]
I have not experienced this and can not reproduce it.

What platform are you on ?

**Comment by pavlik** [comment]
@abiosoft Ubuntu 14.04 64 bit

**Comment by abiosoft** [comment]
@pavlik Ensure the Caddy you're using includes the Git plugin.

**Comment by pavlik** [comment]
@abiosoft caddy 0.8 beta 4 with last ver of your pluggin installed by caddyext & then I make `go install` in caddy dir for new executable ver of caddy

**Comment by abiosoft** [comment]
Sorry follow this steps, I think you're using an outdated version.
```
$ caddyext install git
$ go get github.com/mholt/caddy
```

Then try again.

**Comment by pavlik** [comment]
@abiosoft I remove `caddy` from bin directory, then I follow your instructions. Then `go install` for caddy. But this error still happened.

**Comment by abiosoft** [comment]
Caddy 0.8 is released. Can you try downloading from Caddy's site now and trying again.

Or
```wget -O caddy.tar.gz "https://caddyserver.com/download/build?os=linux&arch=amd64&features=git"``` 

Then extract the tar and try again.

**Comment by pavlik** [comment]
@abiosoft with caddy 0.8 al works fine! Thank you!
