### ISSUE TITLE
BitBucket WebHook returns 403 Forbidden

### ISSUE THREAD

**Issue by Sirikon** [abiosoft/caddy-git#16]
This is a PHP website using HHVM via FastCGI with a Bolt.cm installation.

SSH keys are properly configured in both VPS and BitBucket

My Caddyfile:

```
http://vps234794.ovh.net {
        gzip

        git {
                repo     git@bitbucket.org:myuser/mywebsite.git
                branch   master
                key      /root/.ssh/id_rsa
                path     .
                hook     /bitbucketwebhook
        }

        log ./access.log
        errors ./error.log

        root ./mywebsite

        rewrite {
                r /thumbs/(.*)$
                to /index.php?{query}
        }

        rewrite {
                r \.(?:ico|ICO|css|CSS|js|JS|gif|GIF|jpe?g|JPE?G|png|PNG|ttf|TTF|woff|WOFF|woff2|WOFF2)$
                to /{path}?{query}
        }

        rewrite {
                r /phpmyadmin/(.*)$
                to /{path}?{query}
        }

        rewrite {
                r .*
                to /index.php?{query}
        }

        rewrite {
                r /bolt/(.*)$
                to /index.php?{query}
        }

        rewrite {
                r /async/(.*)$
                to /index.php?{query}
        }

        fastcgi / /var/run/hhvm/sock php
}
```

But every time I retry the webhook, Caddy responds with 403 Forbidden:

![captura](https://cloud.githubusercontent.com/assets/1157382/12217219/0b4abb88-b6fa-11e5-9d2b-bfefcdcbfa4f.PNG)

Using Caddy 0.8 with Git module downloded from the website
Debian 8 64bits

**Comment by abiosoft** [comment]
The only time that can happen is if the request comes from an invalid BitBucket ip i.e. an ip not present under "Triggering Webhooks" here https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html.

Can you enable error log and check the error message ?

**Comment by Sirikon** [comment]
@abiosoft Do you mean Caddy error.log file, that is configured on my Caddyfile? it's empty

**Comment by abiosoft** [comment]
Oh really? That is strange.

Let's add `{remote}` to access log format and let's see the value.
```
log / ./access.log "{proto} Request: {method} {path}"
```

**Comment by Sirikon** [comment]
The requests to /bitbucketwebhook doesn't get registered in access.log... :S

**Comment by abiosoft** [comment]
Is the access log also empty or only not including the bitbucket request? Also, verify that the user starting Caddy can write to the access and error log files.

I do not expect either to be empty.

**Comment by Sirikon** [comment]
Access log is not empty, it have the rest of the requests' logs to the PHP site, and the user running caddy is root

**Comment by abiosoft** [comment]
Let's do an hack to get the remote ip address in the log. Comment out the webhook line from the config and resend the payload. That way, the git middleware won't interrupt the request.

**Comment by Sirikon** [comment]
The Bitbucket's IP is `131.103.20.165`

**Comment by abiosoft** [comment]
That's supposed to be valid. Could be a bug. Let me investigate.

Thanks.

**Comment by abiosoft** [comment]
All tests I've done so far points to the fact that no error should occur.

I should be able to look more into this in a few days.

**Comment by evanpaschke** [comment]
+1 I'm experiencing the same behavior running the [caddy 0.8.1 + git binary](https://caddyserver.com/download/build?os=linux&arch=amd64&features=git) with the following config:
```
mydomain.com {
  root website
  errors errors.log
  log access.log
  git git@bitbucket.org:me/website.git {
    hook /push
    key /key/path/id_rsa
  }
}
```

**Comment by abiosoft** [comment]
Now that this is confirmed by another user, I'll investigate more.

I've been busy recently but hopefully in a few days.

Thanks.

**Comment by captncraig** [comment]
Is there any other proxy in between bitbucket and caddy by any chance? something like ngrok perhaps? Anything that would rewrite the ip and add an X-Forwarded-For header may break something like this.

**Comment by sirtux** [comment]
Hi, I've also run into this problem,
and I debugged via tcpdump - the request comes from lb01-ash.bitbucket.org, which is 131.103.20.165,
so that at least the request comes from the right IP.

**Comment by Sirikon** [comment]
@sirtux @captncraig It's a new VPS hosted in OVH with Debian 8 without any proxy, ngrok, vpn or anything.

Could I do anything in my actual failing environment to target the issue? Any known networking/routing/whatever problem known in OVH VPS services?

**Comment by abiosoft** [comment]
Sorry guys, still busy with some other things. :( I've not been able to troubleshoot using a live server.

Anyone willing to build from source and comment out the IP validation codes to see if it works ?

**Comment by Sirikon** [comment]
@abiosoft Is this how it's done?:

```
go get github.com/mholt/caddy
go get -u github.com/caddyserver/caddyext
caddyext install git
cd /folder-with-caddyfile
caddy
```

**Comment by abiosoft** [comment]
That works fine. 

But if you wanna be continuously meddling with the source, [caddydev](https://github.com/caddyserver/caddydev) may suit better.

**Comment by Sirikon** [comment]
@abiosoft Removed [this](https://github.com/abiosoft/caddy-git/blob/master/bitbucket_hook.go#L12-L16), and [this](https://github.com/abiosoft/caddy-git/blob/master/bitbucket_hook.go#L7). And replaced [this](https://github.com/abiosoft/caddy-git/blob/master/bitbucket_hook.go#L100-L112) with `return true`.

The webhook worked... something is wrong [here](https://github.com/abiosoft/caddy-git/blob/master/bitbucket_hook.go#L99-L113):

```go
func (b BitbucketHook) verifyBitbucketIP(remoteIP string) bool {
	ipAddress := net.ParseIP(remoteIP)
	for _, cidr := range bitbucketIPBlocks {
		_, cidrnet, err := net.ParseCIDR(cidr)
		if err != nil {
			Logger().Printf("Error parsing CIDR block [%s]. Skipping...\n", cidr)
			continue
		}

		if cidrnet.Contains(ipAddress) {
			return true
		}
	}
	return false
}
```

**Comment by abiosoft** [comment]
Thanks :smile: You can keep using your custom binary till it is fixed.

I later added instructions to build from source using caddydev [here](https://github.com/abiosoft/caddy-git/blob/master/BUILDING.md).

**Comment by Sirikon** [comment]
@abiosoft Just made a pull request with the fix, the explanation is there :smile:

**Comment by abiosoft** [comment]
You're awesome :+1:

**Comment by abiosoft** [comment]
You're gonna need to build from source for now. It'll take a while for Caddy's download page to include the updated version.

**Comment by Sirikon** [comment]
@abiosoft Thanks to you! :+1:
