### ISSUE TITLE
App running by plugin crashed & not restart

### ISSUE THREAD

**Issue by pavlik** [abiosoft/caddy-git#17]
Hi! Application runned by Git add-on goes down after several hours & don't restart.

This is error log of application (created by caddy)
`13/Jan/2016:19:57:22 +0300 [ERROR 502 /] unreachable backend`

This is few strings from caddy.log
```
[GIN-debug] Listening and serving HTTP on :9000
[GIN-debug] [ERROR] listen tcp :9000: bind: address already in use
```

This is Caddyfile
```
mimozaflowers.ru, www.mimozaflowers.ru {
        root /root/gocode/src/github.com/pavlik/mimozaflowers
        gzip
        log /var/log/mimoza_access.log

        errors {
                log /var/log/mimoza_error.log
                #404 404.html # Not Found
        }

        git {
                path ./
                repo https://github.com/pavlik/mimozaflowers
                hook /webhook secret
                then go install
                then_long /root/gocode/bin/mimozaflowers
        }

        proxy / localhost:9000
}
```

This is my app `https://github.com/pavlik/mimozaflowers/blob/master/server.go`

I would appreciate if you help to understand what is the reason off app shutdown...

**Comment by pavlik** [comment]
I doing some experiments. I think this is not problem of your add-on.
If I start my web app it starts on port 9000. Then if I stop server (for example by pressing CTRL+Z), server stopped, but port is not released. Why this happened?

**Comment by abiosoft** [comment]
This could be a Gin framework issue. I'd suggest you leave Caddy and Git out of it for now and be sure the app terminates and releases the port.

Git only attempts to restart thrice. If it didn't succeed, it will ignore the command.

You may want to consider creating an issue on Gin's repository.

**Comment by pavlik** [comment]
You are right, this is problem of my application or Gin framework! I try to ask in Gin community!

**Comment by pavlik** [comment]
Hmm.. I think this is not problem of framework. I rewrite code for Echo framework & have the same problem.
This is answer for my question in Gin repo: https://github.com/gin-gonic/gin/issues/510

Maybe this is caddy problem? When git push new version of some app to caddy git hook > Caddy reload all projects in Caddyfile, yes? And if my application is working need to properly shutdown it & start new version again, right? By brain in the fire :-)

**Comment by abiosoft** [comment]
Can you provide instructions to set up and run your application and let me try to troubleshoot.

**Comment by pavlik** [comment]
Caddyfile & link to my web app you can see in the topic starter post.
P.S. In Echo issue I receive this link http://superuser.com/questions/262942/whats-different-between-ctrlz-and-ctrlc-in-unix-command-line/262948#262948

How git add-on shutting down longterm application?

**Comment by abiosoft** [comment]
I can see your app. How do I build and start it ? I can see it uses godeps, requires a config file e.t.c. I am only concerned about starting it.

**Comment by pavlik** [comment]
this is config.yml
```
clientid: 56abe271f8ac4814912b6dc5e911ed20
clientsecret: ca231f035f794e6498e16f010e19626f
baseurl: https://api.instagram.com/v1
username: mimozaflowers
port: 9000
```

I do: `go build` & then `mimozaflowers`

**Comment by abiosoft** [comment]
Alright thanks. :+1:

**Comment by abiosoft** [comment]
In your logs, did you see any message like this
```
Restart failed after 3 attempts for mimozaflowers
```

**Comment by abiosoft** [comment]
Wait, does the app quit by itself or it happens when the git hook receives a request and Git tries to restart the app. Any idea ?

**Comment by pavlik** [comment]
1. No, I don't see in logs this message
2. Mmm, I think that app trying to restart after receiving git hook..... but...
yesterday I refresh caddy version I start server.... after 5 hours mimozaflowers goes down (in this period I don't push any changes)

**Comment by pavlik** [comment]
This is some log of supervisor.log
```
2016-01-14 02:20:47,021 INFO spawned: 'caddy' with pid 22828
2016-01-14 02:20:48,762 INFO success: caddy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-14 02:20:51,967 INFO exited: caddy (exit status 1; not expected)
2016-01-14 02:20:52,970 INFO spawned: 'caddy' with pid 22903
2016-01-14 02:20:54,710 INFO success: caddy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-14 02:20:57,992 INFO exited: caddy (exit status 1; not expected)
2016-01-14 02:20:58,995 INFO spawned: 'caddy' with pid 22979
2016-01-14 02:21:00,812 INFO success: caddy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-14 02:21:04,369 INFO exited: caddy (exit status 1; not expected)
2016-01-14 02:21:05,372 INFO spawned: 'caddy' with pid 23054
2016-01-14 02:21:07,134 INFO success: caddy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2016-01-14 02:21:10,484 INFO exited: caddy (exit status 1; not expected)
2016-01-14 02:21:11,486 INFO spawned: 'caddy' with pid 23130
```

**Comment by abiosoft** [comment]
That supervisor log looks like caddy itself is the one crashing and restarting, not your app.

**Comment by pavlik** [comment]
I think caddygoes into an infinite loop restart, because can't init mimozaflowers app:
a piece of caddy.log:
```
From https://github.com/pavlik/mimozaflowers
 * branch            master     -> FETCH_HEAD
Already up-to-date.
2016/01/15 00:33:12 https://github.com/pavlik/mimozaflowers.git pulled.
2016/01/15 00:33:12 Command 'go install' successful.
2016/01/15 00:33:12 Command '/root/gocode/bin/mimozaflowers ' successful.
9000
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET   /js/*filepath             --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (5 handlers)
[GIN-debug] HEAD  /js/*filepath             --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (5 handlers)
[GIN-debug] GET   /css/*filepath            --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (5 handlers)
[GIN-debug] HEAD  /css/*filepath            --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (5 handlers)
[GIN-debug] GET   /                         --> main.recentMedia (5 handlers)
[GIN-debug] Listening and serving HTTP on :9000
[GIN-debug] [ERROR] listen tcp :9000: bind: address already in use
```

**Comment by abiosoft** [comment]
What we need to find out is why Caddy is crashing. I have been able to reproduce the issue.

Caddy crashes but mimozaflowers is still alive. So whenever supervisord restarts Caddy, Git tries to start your app without success.

Try this:
Try to start your app twice, you will see that you'll get that same output.

**Comment by pavlik** [comment]
My try result:
If first instance is running when I try to run second instance of mimozaflowers, in second instance I receive this error:
```
FATAL|echo|listen tcp :9000: bind: address already in use
exit status 1
```

But first instance is live & working.

But in production server instance is goes down & in web browser I receive `502 error`

**Comment by abiosoft** [comment]
Can you separate the app from caddy entirely. Maybe start it separately with supervisord. Let's leave it for a while and see if it is gonna crash.

**Comment by pavlik** [comment]
I listened to your recommendations & run the application separately.
And in supervisord con file changes stop signal param from QUIT to INT.
Let's see what will happen.

**Comment by dolmen** [comment]
@pavlik Ctrl+Z does not stop a process. It only freezes it, so its ressources (such as network ports) are not freed because you can unfreeze it later.

**Comment by abiosoft** [comment]
This has been inactive for a while. Since nobody else has reported this behaviour, I will close this issue. 

Anyone is welcome to reopen it if the behaviour is reproduced.

**Comment by dolmen** [comment]
@abiosoft This ticket was invalid from the start. It is just a wrong usage of Unix signals: stopping a process (SIGSTOP sent with Ctrl+Z) is not killing it (SIGTERM, SIGKILL).
This is not relevant to Caddy. So this ticket must be definitely buried.
