### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by adelevie** [abiosoft/caddy-git#18]
I am new to Caddy and would like to use this add on. Caddy's own docs don't seem to specify how to install add-ons. 

Is there a generic way to do this? If not, how can install this add-on?

**Comment by captncraig** [comment]
The caddy download page has the ability to build a caddy binary that has the git plugin built in for any platform: https://caddyserver.com/download. Otherwise you could build it yourself using github.com/caddyserver/caddyext, but the download is really easiest.

**Comment by abiosoft** [comment]
I believe @captncraig's answer is sufficient.
