### ISSUE TITLE
Generic Webhook Handler is a Security Risk

### ISSUE THREAD

**Issue by captncraig** [abiosoft/caddy-git#20]
Consider the case where I set up a github webhook with a secret. The github handler decides whether to handle a request based on headers. It will ONLY validate the signature if it determines it is a github request.

If I send a raw POST with no github headers, no signature, and just a json object with a `ref`, the generic handler will pick it up and pull the repository. I would argue that this should not be. It allows anyone on the internet, regardless of authentication of any kind to make my server pull code and execute commands.

**Comment by abiosoft** [comment]
This has been catered from by removing it from defaults in https://github.com/abiosoft/caddy-git/commit/f524bf8758b4862388cb333366d36403a991368c.

Thanks.
