### ISSUE TITLE
Relative to root?

### ISSUE THREAD

**Issue by yitzhakbg** [abiosoft/caddy-git#24]
It says that the [git path is relative to root](https://github.com/abiosoft/caddy-git#user-content-syntax). Root according to my understanding, is the top level directory from which pages are served. If so, the site's sources live in the public page. Isn't that like saying (using hugo as an example):
hugo -d .    etc...
instead of hugo -d public    etc...??
generating the html in the same directory.
Please clarify.

**Comment by abiosoft** [comment]
Yes if you need to clone in the same directory, use `.` as clone path.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    That's nice. Is it safe to assume then that this can be taken
    further, say
    {
      root /var/www/srv/site1
      git site1 {
        path ../../src
      }
    }
    
    directory site1 under /var/www/srv will have to be created manually.
    Caddy gives an initial warning that /var/www/srv/site1 does not
    exist (yet). Html will be generated into and served from
    /var/www/srv/site1 from the source tree (given by the "path"
    directive) residing at /var/www/src/site1. Did I get that right.
    Wouldn't uncoupling the source path from the root would add
    flexibility?
    
    On 27/1/16 17:07, Abiola Ibrahim wrote:
    
    
      Yes if you need to clone in the same directory, use .
        as clone path.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by abiosoft** [comment]
Yeah, that works too.

Thanks.
