### ISSUE TITLE
Doesn't serve with caddy-git

### ISSUE THREAD

**Issue by yitzhakbg** [abiosoft/caddy-git#25]
This builds the site but doesn't serve:
http://levpoem.co.il {
  root /var/www/srv/levpoem
  tls off
  git {
    repo https://github.com/yitzhakbg/levpoem.git
    path ../../src/levpoem # relative to root. In actuality, /var/www/src/levpoem
    branch master
    then runhugo
  }
}
When I comment out caddy-git, the site just built (above) serves OK:
http://levpoem.co.il {
  root /var/www/srv/levpoem
  tls off
\#  git {
\#    repo https://github.com/yitzhakbg/levpoem.git
\#    path ../../src/levpoem # relative to root. In actuality, /var/www/src/levpoem
\#    branch master
\#    then runhugo
\#  }
}
It only serves when run without caddy-git. Any ideas/suggestions? How to debug?
This doesn't work either (build for localhost, serve on levpoem.co.il):
http://localhost {
  root /var/www/srv/levpoem
  tls off
  git {
    repo https://github.com/yitzhakbg/levpoem.git
    path ../../src/levpoem # relative to root. In actuality, /var/www/src/levpoem
    branch master
    then runhugo
  }
}
http://levpoem.co.il {
  root /var/www/srv/levpoem
  tls off
}

**Comment by yitzhakbg** [comment]
The problem was solved by changing "then" to "then_long". I don't understand why because the run script is continuous

**Comment by abiosoft** [comment]
I assume `runhugo` is a script that blocks.

Thanks. Glad it worked.
