### ISSUE TITLE
caddy is blocked while pull + then command is running

### ISSUE THREAD

**Issue by edrex** [abiosoft/caddy-git#26]
I have a Caddyfile with two sites, one using the git directive. Caddy doesn't start listening for connections until the pull and `then` command have run. The server should not be blocked while the git directive is doing its thing. Possibly, the git directive should do something more fine-grained like serve a 500 at its root path until the command finishes.

**Comment by abiosoft** [comment]
The reason is that I want the user to know if git is successful on startup. Subsequent pulls does not interrupt Caddy.

You can use `then_long` instead to let the command run in background.

**Comment by edrex** [comment]
Hmm, I'd just print an error message instead of exiting. This behavior makes the system unreliable. Circuit breakers and all that.

**Comment by abiosoft** [comment]
You have a point. Especially for automated environments.

**Comment by abiosoft** [comment]
I want to introduce a new config instead. If it is present, it will allow Caddy to start irrespective of what happens.
```
git {
    ...
    ignore_startup_errors
}
```

**Comment by mholt** [comment]
@edrex The behavior of running Startup callbacks before the servers start listening is intentional, since they are used to prepare the server to start serving. If one fails, the server is not prepared to start serving and should not do so.

**Comment by abiosoft** [comment]
Considering there hasn't been activities on this issue for a while and the fact, I will be closing this.

And I also share same view as @mholt.

**Comment by edrex** [comment]
This just offloads the responsibility for ensuring reliability to the user, who will need to run the webhooks stuff in a separate process. *shrugs*

**Comment by mholt** [comment]
Why is that?

**Comment by edrex** [comment]
If the remote git server doesn't respond positively, the local server will fail to start. If you have a git directive in your main server instance, failure to access the remote resource will prevent the entire server coming up. A user can put the git directive in a separate instance on another port (exposed for webhooks) to contain the risk.

**Comment by abiosoft** [comment]
@edrex okay I'll go with my previous proposition. I'll leave it to the user to decide using a config.
