### ISSUE TITLE
BitBucket WebHook returns 403 Forbidden

### ISSUE THREAD

**Issue by mgilbir** [abiosoft/caddy-git#27]
I'm still seeing the behaviour mentioned on #16 with a download of caddy 0.8.2 + git.

Are the changes supposed to be available in the binaries already?

**Comment by mholt** [comment]
@mgilbir I'm so sorry, I haven't updated this plugin on the build server in a long time. I just did tonight, so you should now get the latest and greatest from the Download page on Caddy's website.

**Comment by abiosoft** [comment]
Oops. Thanks @mholt.

**Comment by bc24fl** [comment]
Sorry to comment on a closed issue but didn't want to create a new issue for something similar.  Has this been fixed in caddy .8.2

**Comment by abiosoft** [comment]
Yes, it has.

**Comment by abiosoft** [comment]
@mgilbir Hi, just to be clear. Has this been fixed for you ?
