### ISSUE TITLE
WorkDir of `Then` commands is unclear

### ISSUE THREAD

**Issue by HaMster21** [abiosoft/caddy-git#28]
Hi there :wave: 

Thank you for your work on the git plugin for caddy, this is really useful. However I came across an issue that makes things a little complicated for me.

In your examples in the README, there is the following section:
```
git github.com/user/site {
    path  ../
    then  hugo --destination=/home/user/hugosite/public
}
```

However even when skimming through the code of this Repo I wasn't able to find out what the working directory of the `then` command would be. I expect that to be the directory where the repo is cloned to, but that seems not to be the case. At least not on Windows.

In the example above, it would be nice to know where to point hugo if the site root and the clone directory are not the same. I was trying to automatically build a website with caddy using caddy with the following script

```
localhost:5000 {
    # serve the built hugo site
    root ./www/public

    git https://github.com/my/repo {
        path ..
        # hugo should take the checked out source and build the website according to the config file in the repo
        then hugo
    }
}

**Comment by abiosoft** [comment]
Hi,

You guessed right, the working directory is the github clone path. However, it has not been properly tested on Windows so there is a chance the behaviour is not as expected.

For now, you should be able to pass absolute paths to hugo as a workaround.

**Comment by abiosoft** [comment]
This has been inactive for a while and I will take the silence as a positive response.

Thanks.
