### ISSUE TITLE
Why not http?

### ISSUE THREAD

**Issue by andreynering** [abiosoft/caddy-git#29]
I've tried to pull from Gogs, but the following won't work:

```
http://localhost:4500/...
```

It tries to fetch the https version:

```
https://localhost:4500/...
```

That won't work:

```
fatal: unable to access 'https://localhost:4500/foo/bar': gnutls_handshake() failed: An unexpected TLS packet was received.
```

**Comment by abiosoft** [comment]
Yeah, it converts http url to https. This was based off assumption that https is always available.

You can put Gogs behind Caddy to get https.

**Comment by andreynering** [comment]
Thank you for responding.

I actually already use caddy. But I am trying to access it through the same machine (`localhost`), so I can't access it though caddy and HTTPS, which is only available from outside.

**Comment by abiosoft** [comment]
This is supported now. You can build from source or wait for it to arrive on caddysever.com.

**Comment by andreynering** [comment]
@abiosoft Thank you very much! I'll try it when possible.
