### ISSUE TITLE
Git URL with non-standard port

### ISSUE THREAD

**Issue by mdcollins05** [abiosoft/caddy-git#30]
Is it possible to specify a port to use within the repo URL for SSH?

I've tried using something like `git git@mydomainhere.com:222/mdcollins05/git-repo-name.git {...}` and it still attempts to connect on port 22.

Any suggestions or is this not currently possible? Thanks!

**Comment by abiosoft** [comment]
This was something I did not consider initially. I will need to make it more flexible to allow such urls.

**Comment by abiosoft** [comment]
This is supported now. You can build from source or wait for it to arrive on caddysever.com.

**Comment by mdcollins05** [comment]
Awesome! Thanks a ton.
