### ISSUE TITLE
The plugin is not gitolite friendly

### ISSUE THREAD

**Issue by devsli** [abiosoft/caddy-git#31]
Hi, thanks for awesome plugin!

Unfortunately, it's impossible to use it with default gitolite installation.

Gitolite url: `gitolite@my.awesome.site:repo` is not parsed correctly because of username `gitolite@`:

```
caddy[7380]: 2016/04/12 08:08:38 invalid git url gitolite@4sli.ru:reponame
```

I think it caused by [this code](https://github.com/abiosoft/caddy-git/blob/71e6ca1b36969fe40bcd2fb20fb9ab4f7f2b4483/setup.go#L250) (`git@` username is hardcoded)

When url is replaced with `git@...`, then error is disappeared.
But it's still impossible to clone repo, because there are no `git` user on the server.

**Comment by abiosoft** [comment]
I think this is related to https://github.com/abiosoft/caddy-git/issues/30.

As this is coming up now, I should have time during the weekend to make the urls more flexible.

**Comment by devsli** [comment]
Oh, sorry, I was sure #30 is for non-standard port. I think we could close this one.

**Comment by abiosoft** [comment]
This is supported now. You can build from source or wait for it to arrive on caddysever.com.

**Comment by devsli** [comment]
Great job, thanks a lot!
