### ISSUE TITLE
Always output to console on hook. 

### ISSUE THREAD

**Issue by marcoslater** [abiosoft/caddy-git#32]
It would be useful to have the add-on always output something to the console when a webhook is received. 

Currently, it seems that when a webhook is received for a branch other then the one specified, it is completely ignored and not shown anywhere. 

This caused me to believe the test hooks I was sending were not being received correctly, and spent a significant time debugging it. 

A simple message saying a hook was received and ignored since it is not the configured branch would be very useful in situation like these, as most git software I use sends the "test" webhooks as the last commit to the default (master) branch.

**Comment by abiosoft** [comment]
Good point. I will work on adding it. If you are capable, feel free too.

**Comment by abiosoft** [comment]
By the way, Caddy access log includes webhook requests.

**Comment by abiosoft** [comment]
This has been implemented now. You will need to wait for it to arrive on caddyserver.com.
