### ISSUE TITLE
Can't specify port on URL

### ISSUE THREAD

**Issue by andreynering** [abiosoft/caddy-git#35]
Thank you again for this awesome plugin.

Following up #29 

Now I can use `http://`, but can't specify the port:

```
http://localhost:12345/user/repo.git
```

Gives me the following error:

```
remote: No such host at :80
fatal: repository http://localhost/12345/user/repo.git/ not found
```

I don't know much about the implementation, but maybe you could just use the URL given by the user instead of trying to validate it?

Cheers.

**Comment by abiosoft** [comment]
Oops. I'll fix that now.

Did you build from source ?

**Comment by andreynering** [comment]
> Did you build from source?

Yes

**Comment by abiosoft** [comment]
Try again now :)

**Comment by andreynering** [comment]
It's working now. Thank you again.
