### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by itskenny0** [abiosoft/caddy-git#37]
How would I go about recursively cloning a Git repo that uses submodules?

**Comment by itskenny0** [comment]
Update: `git submodule update --init --recursive` works specified after the command to be run after the clone, but it seems there should be a cleaner solution. Maybe allow specifying command line args to the clone command? Adding --recursive to the git clone should do all we need.

**Comment by abiosoft** [comment]
What I think will be a better solution is to support additional flags to pass to `git clone` command. Considering it will also cater for this https://github.com/abiosoft/caddy-git/issues/22#issue-128650746.

I can add this feature but I cannot guarantee how soon. Anyone is equally free to contribute this feature.

Thanks.

**Comment by abiosoft** [comment]
You can now specify additional cli args to the git clone command using `args` config.
e.g.
```
git {
  ...
  args --recursive
}
```

You will need to wait for this to make it to caddyserver.com/downloads or you build from source.
