### ISSUE TITLE
Default configuration is serving the .git folder.

### ISSUE THREAD

**Issue by itskenny0** [abiosoft/caddy-git#38]
The default configuration is also serving the .git folder. For public repositories, this is not an issue, but it is if you are using private ones.

**Comment by abiosoft** [comment]
Oops.

For now add this to your Caddyfile.

```
# change /.git to the correct path to the .git folder if it is not in the root.
internal /.git 
```

**Comment by abiosoft** [comment]
After another thought, I conclude that this is out of the scope of git middleware. The job of the middleware is just to clone git repository.

I will consider adding a section in the docs advising users to prevent access to .git directory if the repository root is being served.

**Comment by mholt** [comment]
I agree.

And to prevent this, put your site's root in a subfolder of the git repo. It's your job to keep private things private. So if you don't want your .git folder served, you can use `internal` like Abiola suggests, or you can make `public` folder inside the repo where your site lives. This is how we serve the Caddy website.
