### ISSUE TITLE
interval "once"?

### ISSUE THREAD

**Issue by pwFoo** [abiosoft/caddy-git#42]
I try to deploy some small apps with caddy git, but it shouldn't updated automatically. Just should clone the current git repo during deployment.

Could you add an interval "once" option instead of the time in seconds?

**Comment by abiosoft** [comment]
What I'll do instead for now is allow `0` or `-1` for interval to indicate never.
A workaround is a very long time or specify a hook url.

**Comment by pwFoo** [comment]
So 0 or -1 should work with initial clone Düring Start?
Would be fine for me!

Haven't take a look at hook URL, could also work...

**Comment by abiosoft** [comment]
Done. `interval -1` disables periodic pull.

**Comment by pwFoo** [comment]
Thanks!  :)
