### ISSUE TITLE
Use env vars in git plugin / caddyfile 

### ISSUE THREAD

**Issue by pwFoo** [abiosoft/caddy-git#43]
I tried to set the git repo by an env variable like that.
`    git {
        repo     {$repo}
        branch   {$branch}
        path     /
        interval {$interval}
    }`

But it looks like it isn't replaced?
`parse https://$%7Brepo%7D.git: invalid URL escape "%7B"`

**Comment by pwFoo** [comment]
https://github.com/mholt/caddy/pull/907

**Comment by abiosoft** [comment]
Environment variables are supported in Caddyfile. What I am not sure of if it is only limited to uppercase variables.

**Comment by pwFoo** [comment]
Thanks! It works uppercase! :)
