### ISSUE TITLE
Cloning private repository fails

### ISSUE THREAD

**Issue by Falinor** [abiosoft/caddy-git#44]
Hi there,

First, thanks for your great plugin!
I have been running through an issue for 2 days now, which is pretty weird to me.

What I want is **to clone a private repository using my SSH key**.

When I try running caddy as a service (Debian 8) using: `sudo systemctl start caddy`
And then query for its status using: `sudo systemctl status caddy`
Caddy tells me that it could not clone from remote repository because of my public key.
I assumed it was related to my SSH key permissions, so I tried running the exact same command
that my service runs when I start it. Here, Caddy has had no problem cloning my repository.

Unfortunately, I cannot manage to find where the issue is. My caddy.service file is located at
`/etc/systemd/system/caddy.service` and the user as which the service should run is well set.

My caddy.service file:
```
[Unit]
Description=Caddy HTTP/2 web server
Documentation=https://caddyserver.com/docs
After=network.target

[Service]
Restart=on-failure

; User and group the process will run as.
User=inad
Group=www-data

; File descriptors limit.
LimitNOFILE=1048576

ExecStart=/usr/local/bin/caddy -agree=true -email=myemail -conf=/etc/caddy/Caddyfile
ExecReload=/bin/kill -USR1 $MAINPID

StartLimitInterval=600

[Install]
WantedBy=multi-user.target
```

My Caddyfile:
```
domain.com {
    root /var/www/my-site

    git my-git-repo.git {
        key    /home/inad/.ssh/id_rsa
    }
}
```

The file `/home/user/.ssh/id_rsa` has permissions 600, and owner:group is inad:inad.
As I said, when I run manually the ExecStart command from caddy.service in my shell,
it correctly clones the repository, but using systemctl, it does not.

Any help is welcome, thank you in advance!

**Comment by abiosoft** [comment]
Firstly, the fact that running the command directly works indicates that this is due to an issue with systemd, not caddy or git.

This is very weird but I still think it is a permission issue. Can you share the exact error message you got ?

**Comment by Falinor** [comment]
I do think the same way, still I do not understand why the service would run as another user,
because I notified it to run as **inad**, which is my account.
Here is the message:

```
$ sudo systemctl status caddy.service -l
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled)
   Active: active (running) since Sun 2016-07-03 22:30:02 CEST; 12s ago
     Docs: https://caddyserver.com/docs
 Main PID: 14392 (caddy)
   CGroup: /system.slice/caddy.service
           ├─14392 /usr/local/bin/caddy -agree=true -email=myemail -conf=/etc/caddy/Caddyfile
           ├─14421 /bin/bash /tmp/caddy659591750
           ├─14424 ssh-keyscan -t rsa dsa bitbucket.org
           └─14425 sort -u - /home/inad/.ssh/known_hosts

Jul 03 22:30:02 vps263107.ovh.net caddy[14392]: Activating privacy features... done.
Jul 03 22:30:07 vps263107.ovh.net caddy[14392]: Cloning into '/var/www/php-project-client'...
Jul 03 22:30:13 vps263107.ovh.net caddy[14392]: Permission denied (publickey).
Jul 03 22:30:13 vps263107.ovh.net caddy[14392]: fatal: Could not read from remote repository.
Jul 03 22:30:13 vps263107.ovh.net caddy[14392]: Please make sure you have the correct access rights
Jul 03 22:30:13 vps263107.ovh.net caddy[14392]: and the repository exists.
Jul 03 22:30:13 vps263107.ovh.net caddy[14392]: 2016/07/03 22:30:13 exit status 128
```

Thanks for your quick answer.

**Comment by abiosoft** [comment]
@Falinor Any luck with this ?

**Comment by nidheeshdas** [comment]
Hi, 
I'm getting similar problem.

```
Sep 04 10:09:59 XXXas.com systemd[1]: Stopped Caddy HTTP/2 web server.
Sep 04 10:09:59 XXXXdas.com systemd[1]: Started Caddy HTTP/2 web server.
Sep 04 10:09:59 XXXdas.com caddy[6697]: Activating privacy features... done.
Sep 04 10:10:02 XXXdas.com caddy[6697]: Host key verification failed.
Sep 04 10:10:02 XXXXdas.com caddy[6697]: fatal: Could not read from remote repository.
Sep 04 10:10:02 nXXXXs.com caddy[6697]: Please make sure you have the correct access rights
Sep 04 10:10:02 niXXXas.com caddy[6697]: and the repository exists.
Sep 04 10:10:02 niXXXs.com caddy[6697]: 2016/09/04 10:10:02 exit status 1
Sep 04 10:10:04 XXXas.com systemd[1]: Stopping Caddy HTTP/2 web server...
Sep 04 10:10:04 nXXX.com caddy[6697]: 2016/09/04 10:10:04 [INFO] SIGTERM: Terminating process
Sep 04 10:10:04 niXXXcom systemd[1]: Stopped Caddy HTTP/2 web server.
Sep 04 10:10:04 niXXX.com systemd[1]: Started Caddy HTTP/2 web server.
Sep 04 10:10:04 niXX.com caddy[6746]: Activating privacy features... done.
Sep 04 10:10:07 nirXXcom caddy[6746]: Host key verification failed.
Sep 04 10:10:07 nirXXXom caddy[6746]: fatal: Could not read from remote repository.
Sep 04 10:10:07 nXXXs.com caddy[6746]: Please make sure you have the correct access rights
Sep 04 10:10:07 nXXXdas.com caddy[6746]: and the repository exists.
Sep 04 10:10:07 niXasX.com caddy[6746]: 2016/09/04 10:10:07 exit status 1
```

```
root@XXXXas:/var/www/faqify# sudo systemctl status caddy.service -l
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2016-09-04 10:11:00 EDT; 7s ago
     Docs: https://caddyserver.com/docs
 Main PID: 7124 (caddy)
    Tasks: 9
   Memory: 3.9M
      CPU: 247ms
   CGroup: /system.slice/caddy.service
           ├─7124 /usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp
           ├─7165 /bin/bash /tmp/caddy396642904
           ├─7168 ssh-keyscan -t rsa dsa gitlab.com
           └─7169 sort -u - /etc/ssl/caddy/.ssh/known_hosts
```

It says `Host key verification failed.` and I found a `known_hosts` file at the above location. From where does this `known_hosts` file come from? Is that a list of all known keys?

**Comment by abiosoft** [comment]
The known host file comes from here https://github.com/abiosoft/caddy-git/blob/master/scripts.go#L116-L120.

**Comment by Falinor** [comment]
Hey!

I managed to solve the problem for a while, fortunately.
In order to let anyone viewing this post understand and get started, I will explain the whole process.

My caddy binary is at `/usr/local/bin/caddy`.

#### Create caddy user

`$ sudo useradd -m -d /var/lib/caddy -r -G www-data caddy` should do the trick

#### Create caddy service

On my Debian 8 Jessie, I have a file defining my service at `/etc/systemd/system/caddy@.service`.
This file should atleast contain the following:

```
[Unit]
Description=<your description>
After=network.target

[Service]
Restart=on-failure

; User and group the process will run as.
User=%i
Group=www-data

LimitNoFile=<your limit>

ExecStart=/usr/local/bin/caddy -agree -email <your email> -conf /etc/caddy/Caddyfile -pidfile /var/run/caddy/caddy.pid
ExecReload=/bin/kill -USR1 $MAINPID

PIDFile=/var/run/caddy/caddy.pid

StartLimitInterval=600

[Install]
WantedBy=multi-user.target
```

This file contains a minimal configuration for caddy@ service.
Let's move on!

#### The Caddyfile

I wrote in the service that my configuration Caddyfile should be `/etc/caddy/Caddyfile`.
This is because I like to manage all my sites in one place. Let's create it.

A minimal Caddyfile using git with an ssh key could look like that:

```
domain.com {
  root    /var/www/domain.com/
  log      /var/log/domain.com/access.log
  errors /var/log/domain.com/errors.log
  gzip

  git <your-git-repo.git> {
    key /var/lib/caddy/.ssh/domain.com.id_rsa
  }
}
```

I prefer using deployment keys, it has pros and cons. Now, we should create a new ssh key for caddy user. The command could be the following:

`$ sudo -Hu caddy ssh-keygen -t rsa -b 4096 -C "domain.com" -f "domain.com.id_rsa"`

This command will create a pair of ssh files containing the public and private keys of caddy user. Give them appropriate rights. My private key file has `600` and my public one has `644`. Do not create a password, leave it blank. [This is a con of deployment keys.](https://developer.github.com/guides/managing-deploy-keys/)

Lastly, verify permissions and ownership on `/var/www` and try it.

```
$ sudo systemctl enable caddy@caddy
$ sudo systemctl restart caddy@caddy
$ sudo journalctl -fu caddy@caddy
```

Wait and see after the last command. Please tell me if that worked for you!

**Comment by abiosoft** [comment]
That's good to hear and I think its safe to close this issue.

@nidheeshdas, can you try the instructions above as well.
