### ISSUE TITLE
Clone outside of webroot

### ISSUE THREAD

**Issue by martijnve** [abiosoft/caddy-git#47]
My repo contains some stuff that I don't want to serve. I only want to serve the www sub-folder. Right now I have path set to ../git and then I copy the relevant data to the webroot.

Ideally I would checkout to $SOME_PATH/git and then have my webroot be $SOME_PATH/git/www but that would also require caddy to boot when the root doesn't exist (currently attempting that crashes caddy).

Can we have a param to set the path relative to the working-directory instead of to the webroot?

**Comment by abiosoft** [comment]
> but that would also require caddy to boot when the root doesn't exist (currently attempting that crashes caddy).

Can I have the error message you're getting ? I have done this one number of occasions and should not be the case.

**Comment by martijnve** [comment]
Ah sorry for the confusion. The browse directive causes it not to boot when the root doesn't exist not caddy itself.

So no problem there.

**Comment by abiosoft** [comment]
Then I think we need to fix **browse** instead. It should return relevant error (404), not crash the server.

**Comment by abiosoft** [comment]
Yeah, I will consider adding a config to toggle absolute/relative path.  I think that should be enough.

**Comment by martijnve** [comment]
A toggle would be great.
I will report the browse bug as a caddy issue.

**Comment by abiosoft** [comment]
You can now clone to absolute path using `use_absolute_path` config.
e.g.
```
git {
  ...
  use_absolute_path
}
```

You will need to wait for this to make it to caddyserver.com/downloads or you build from source.

**Comment by abiosoft** [comment]
Update: after considerations I discarded `use_absolute_path` and uses the path directly.
Absolute path is now supported if specified.
e.g. 
`/path/to/clone` -> absolute
`clone` -> relative
