### ISSUE TITLE
Option to clone the latest commit only?

### ISSUE THREAD

**Issue by peterychuang** [abiosoft/caddy-git#48]
It seems a bit unnecessary to have the full git history cloned to a production server, especially if the commit history grows long. I'm wondering if it's a good idea to have the option to use ```git clone --depth=1``` instead of cloning everything.

Thanks.

**Comment by abiosoft** [comment]
Yeah it is. This should make it in soon.

**Comment by abiosoft** [comment]
You can now specify additional cli args to the git clone command using `args` config.
e.g.
```
git {
  ...
  args --depth=1
}
```

You will need to wait for this to make it to caddyserver.com/downloads or you build from source.
