### ISSUE TITLE
Add BitBucket hook support

### ISSUE THREAD

**Issue by ApfelUser** [abiosoft/caddy-git#5]
^ Title explains everything. Same as for GitLab and GitHub.

Some Links:

* [General Explanation](https://confluence.atlassian.com/display/BITBUCKET/Manage+Webhooks)
* [Documentation](https://confluence.atlassian.com/display/BITBUCKET/Event+Payloads)
* [Demo Listener Project](https://bitbucket.org/atlassianlabs/webhook-listener)

**Comment by abiosoft** [comment]
@ApfelUser I'll implement it but it might take a few days for me to have the chance to add it. However, if you feel like contributing it, feel free.

**Comment by mholt** [comment]
This is done, right? #7?

**Comment by abiosoft** [comment]
Yeah.
