### ISSUE TITLE
Args for `git pull` - not just clone

### ISSUE THREAD

**Issue by OJFord** [abiosoft/caddy-git#53]
I'd like to be able to supply `-s recursive -X theirs` as an argument to `git pull`. (In fact it's maybe worth considering as a default?)

This isn't currently possible at all, to the best of my knowledge, since although:
```conf
[pull]
    twohead = theirs
```
gives the latter (and can be supplied as a `--template` in `Args`), it still results in an error because `-s recursive` is missing.

It's also not immediately clear that `Args` should refer to `clone`, and clone alone, so my suggestion is to deprecate it and have `CloneArgs` and `PullArgs`.

Alternatively, since I think this is a good default, change `pull` to `fetch` and `checkout`.

I'm not familiar with Go, but I've had a look at the code and I think I could probably manage a PR if this does sound like something your interested in supporting.

Many thanks,

**Comment by abiosoft** [comment]
Good point you've raised there, though the document indicates the args are for clone.

How does changing `pull` to `fetch` and `checkout` help your scenario ?

**Comment by OJFord** [comment]
Yes, the documentation's good @abiosoft, sorry I should have been more clear, but I meant when reading code it's not clear unless familiar with the particular argument used.

`pull` attempts a merge in the presence of local changes; if it instead `fetch`ed (without moving `HEAD`) and then `checkout`ed the remote copy, local changes would be lost in favour of remote, just as with `pull -X theirs`.

My goal is just to ignore anything I've done tinkering around on the server, or that's been overwritten by something (presumably accidentally) and replace it with the latest revision under version control.

**Comment by asdofindia** [comment]
I wanted to `--allow-unrelated-histories` so that my static site which's generated and (force)-pushed to a branch works. But, of course, the arg goes to clone and not to pull

**Comment by abiosoft** [comment]
I don't wanna introduce a breaking change, would've just introduced more specific `clone_args` and `pull_args` while removing `args`.

**Comment by OJFord** [comment]
That sounds good; potentially solves some problems people might have the other way around too.

**Comment by abiosoft** [comment]
It has been implemented and should show up in Caddy soon.
