### ISSUE TITLE
Use Git in Caddy-docker

### ISSUE THREAD

**Issue by pascalandy** [abiosoft/caddy-git#61]
Hi,

I use caddy-docker for a while now and I love it. I want to use the git add-on.

**My Caddyfile**

```
http://example.com {

        root example

        git {
        repo git@github.com:example-org/staticsite
        branch master
        key /etc/id_rsa
        interval 30
        }
}
```

When I `Docker exec`:

```
/srv
total 8
-rw-r--r--    1 root     root         516 May 19 15:05 index.html
drwxr-xr-x    6 root     root        4.0K Jun 14 20:10 example/

/srv/example/www
total 16
drwxr-xr-x    2 root     root        4.0K Jun 14 20:02 css/
drwxr-xr-x    2 root     root        4.0K Jun 14 20:02 images/
-rwxr-xr-x    1 root     root        3.6K Jun 14 20:02 index.html*
drwxr-xr-x    2 root     root        4.0K Jun 14 20:02 js/
```

Two challenge here.

1) As I use one container for 1 site, I want caddy to accept traffic for any request, not only example.com. So the Caddyfiel should use 0.0.0.0

2) I don’t know how caddy is suppose to know where to serve files over /srv/example/www

Here is how I imagine it could work but the container does not even run with the **Caddyfile**: 

```
0.0.0.0
root /svr

    git {
        repo git@github.com:example-org/staticsite /svr
        branch master
        key /etc/id_rsa
        interval 30
    }

```

Thank you in advance!
https://twitter.com/askpascalandy

**Comment by abiosoft** [comment]
Your git syntax is wrong. You need to remove `path` from `repo` and specify it separately. `path` is relative to root or absolute if it starts with `/`.
You can check the documentation https://caddyserver.com/docs/http.git.

**Comment by pascalandy** [comment]
Thanks for this quick answer :)

I think you took my imaginary Caddyfile (**#3**) as my actual setup. I know it's not working. It's only the way I feel it could work. 

**#1** is my actual Caddyfile :)

**Comment by pascalandy** [comment]
Here is the answer I was looking for :)

```
0.0.0.0
browse
tls off

git {
        repo git@github.com:firepress-org/splashy
        path /var/www/src/static
        branch master
        key /etc/id_rsa
        then cp -R -u /var/www/src/static/www/. /srv/.
        interval 30
}
```

I find it a bit hacky as I need to copy manually the files.
Is there a way to avoid `then cp -R -u /var/www/src/static/www/. /srv/.`
Checkout the [git repo](https://github.com/firepress-org/splashy). I need to server content within www

**Comment by abiosoft** [comment]
Why copy when you can clone directly to the `/srv/www` ? Also, some of the configs are default and you can remove them.
```
0.0.0.0
browse
tls off
root /srv/www

git git@github.com:firepress-org/splashy /srv/www {
  key /etc/id_rsa
  interval 30
}
```

**Comment by pascalandy** [comment]
Almost there! I see this:

![screen shot 2017-06-15 at 9 14 01 pm](https://user-images.githubusercontent.com/6694151/27207826-a15d7e74-520f-11e7-9154-eb7e9de03ef1.png)

When I click on the `www` the site is loading normally.

I tried all kinds of path interactions but I can't crack the code yet. Many thanks!
