### ISSUE TITLE
Unable to clone https repo w/ auth info in URL

### ISSUE THREAD

**Issue by riptidewave93** [abiosoft/caddy-git#64]
Hello,

Currently I am unable to use caddy git to clone a repo where authentication is passed in the repo URL.

Config:
```
site.com {
    tls off
    root /srv/domain/
    git https://user:pass@gitlab.X.com/project/site.com.git
}
```

Caddy Output:
```
2017/07/11 17:46:54 [WARNING] TLS disabled for http://
Cloning into '/srv/domain'...
fatal: could not read Password for 'https://user..pass@gitlab.X.com': No such device or address
2017/07/11 17:46:54 exit status 128
Cloning into '/srv/domain'...
fatal: could not read Password for 'https://user..pass@gitlab.X.com': No such device or address
2017/07/11 17:46:54 exit status 128
Cloning into '/srv/domain'...
fatal: could not read Password for 'https://user..pass@gitlab.X.com': No such device or address
2017/07/11 17:46:54 exit status 128
2017/07/11 17:46:54 exit status 128
2017/07/11 17:46:55 [WARNING] Root path does not exist: /srv/domain/
Activating privacy features... done.
```

Tested on version 0.10.4

**Comment by abiosoft** [comment]
Thanks for reporting this.

**Comment by abiosoft** [comment]
I think I will simply make this easier by not allow caddy-git to intelligently modify the URLs.
At the moment caddy-git automatically changes the repo url to ssh format when ssh key is set and vice versa.

The only downside is that it will be up to users to set it accordingly, and I do not think that should be a big deal.

**Comment by anakinjay** [comment]
Just came here to report this exact same issue.  Anyone know of a workaround?

**Comment by abiosoft** [comment]
Okay, I'll be doing this https://github.com/abiosoft/caddy-git/issues/64#issuecomment-322168247.

**Comment by abiosoft** [comment]
This is fixed now. Should be deployed to caddyserver.com in few minutes.
