### ISSUE TITLE
 Remote URL

### ISSUE THREAD

**Issue by griffins** [abiosoft/caddy-git#71]
How does it get the repo origin?

Am having errors that there is another repo on the same path, I had just cloned the repo manually at first, i want caddy.git to keep it up to date, whats wrong that am doing?

```

sub.domain.tld {
        tls email@example.com
        gzip
        root /var/www/project_dir/public_dir
        git {
                repo git@gitlab.com:username/repo.git
                hook /_webhook secret
                path ../
                key /home/user/.ssh/key
        }
        fastcgi / 127.0.0.1:9000 php
        
        rewrite {
                to {path} {path}/ /index.php?{query}
        }

        errors /var/log/caddy/errors.log
        log /var/log/caddy/access.log
}
```

**Comment by abiosoft** [comment]
What is the error output ?

**Comment by griffins** [comment]
Sorry i didnt post the ouput

```
Cloning into '[removed]'...
ssh: Could not resolve hostname gitlab.com:user_removed: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
2017/08/26 17:21:56 exit status 128
2017/08/26 17:21:56 exit status 128
```

**Comment by griffins** [comment]
It tries to converts the ssh url to http.

**Comment by abiosoft** [comment]
Yes, if you are not authenticating with private key, you are expected to use http url.

Either change the url to http scheme or specify path to private key.

**Comment by griffins** [comment]
i added the ssh key. Let me update my caddy file

**Comment by griffins** [comment]
If i try to specify the repo url as``` https://username:password@gitlab.com/username/repo.git``` i get
```
Cloning into 'project_dir'...
fatal: unable to access 'https://username:password@gitlab.com:username/repo.git/': Illegal port number
2017/08/26 17:36:35 exit status 128
2017/08/26 17:36:35 exit status 128
```

I guess there might be a bug in the way you parsing the port number.

**Comment by abiosoft** [comment]
Can you share your entire Caddyfile, the way it is right now.

**Comment by griffins** [comment]
```
finance.mibc.co.ke {
        tls oringogriffins@gmail.com
        gzip
        root /var/www/mibc/public
        git {
                repo git@gitlab.com:griffins/micro.git
                hook /_webhook 37gd73e3n
                path ../
                key /root/.ssh/id_rsa
        }

        fastcgi / 127.0.0.1:9000 php
         rewrite {
                to {path} {path}/ /index.php?{query}
        }

        errors /var/log/caddy/errors.log
        log /var/log/caddy/access.log
}

```

**Comment by abiosoft** [comment]
Then the error log you pasted above should not have been generated by that Caddyfile. Because it will attempt ssh authentication, not https.

**Comment by griffins** [comment]
I have tried two methods, let me post the one with the https

```
finance.mibc.co.ke {
        tls oringogriffins@gmail.com
        gzip
        root /var/www/mibc2/public
        git {
                repo https://griffins:mypasswordforgitlab@gitlab.com:griffins/micro.git
                hook /_webhook 1654635gd63
                path ../
                key /root/.ssh/id_rsa
        }

        fastcgi / 127.0.0.1:9000 php
         rewrite {
                to {path} {path}/ /index.php?{query}
        }

        errors /var/log/caddy/errors.log
        log /var/log/caddy/access.log
}

**Comment by abiosoft** [comment]
I think I've reproduced this. Probably introduced in my recent update yesterday.

Thanks for taking the time. Working on a fix.

**Comment by griffins** [comment]
thanks, welcome.

**Comment by abiosoft** [comment]
Fixed, should be available for download on caddyserver.com in few minutes.

**Comment by abiosoft** [comment]
And it is.
> Fixed, should be available for download on caddyserver.com in few minutes.

**Comment by griffins** [comment]
lemme confirm if the fix actually works

**Comment by griffins** [comment]
Still having the same issue.

**Comment by griffins** [comment]
Mind re-opening the issue?

**Comment by abiosoft** [comment]
oh really ?

Same Caddyfile and output ?

**Comment by abiosoft** [comment]
Where are you downloading Caddy from ?

**Comment by griffins** [comment]
```curl https://getcaddy.com | bash -s http.git```

**Comment by abiosoft** [comment]
I just downloaded and got an expected behaviour. Can you kindly verify you are indeed not referencing an older binary by first doing `rm $(which caddy)`.

**Comment by griffins** [comment]
done- guess its the same binary. Maybe its the caddy build server caching

**Comment by abiosoft** [comment]
Do you mind trying out in a fresh environment. A container maybe.

**Comment by griffins** [comment]
let me try that on my dev machine.

**Comment by griffins** [comment]
Am able to clone now. Seems my caddyfile had an error, ```gitlab.com:griffins``` instead of ```gitlab.com/griffins```

**Comment by griffins** [comment]
One last thing, how comes gitlab says the ```Hook executed successfully but returned HTTP 400 400 Bad Request``

**Comment by griffins** [comment]
I had to say ```hook_type generic``` , thanks a lot for the support. You have a follow
