### ISSUE TITLE
Testing locally, getting errors

### ISSUE THREAD

**Issue by greggman** [abiosoft/caddy-git#73]
so first I wanted to just test locally so I created a folder, I manually cloned my repo

     mkdir test
     cd test
     git clone /path/to/repo .

The Caddyfile had this

```
  git {
    repo /path/to/repo
    path ../
    interval -1
    hook /pull
    hook_type generic
    then_long command "npm run build"
  }
```

but when I ran caddy I got this error

    2017/08/29 01:24:23 another git repo '/path/to/repo.git' exists at .

No idea what that means.

Just as a guess I tried using a file: scheme. I deleted test and started over

     rm -rf test
     mkdir test
     cd test
     git clone file:///path/to/repo .

Then put this in the Caddyfile

```
  git {
    repo file:///path/to/repo
    path ../
    interval -1
    hook /pull
    hook_type generic
    then_long command "npm run build"
  }
```

now I get this error

    2017/08/29 01:26:03 Invalid url scheme file. If url contains port, scheme is required

If I comment out the git section above my Caddyfile works fine

Any ideas?

**Comment by abiosoft** [comment]
`repo` should be path to an online git repo. e.g. Github.

**Comment by greggman** [comment]
Why? Don't you just shell to git? Shouldn't anything on git handles just work? Why do I need to upload my 2Gig repo online just to test?

**Comment by abiosoft** [comment]
The git plugin pulls from a git repository. If you already have the files on your filesystem, then you do not need the plugin.

You can run a local git server if you simply want to test how it works.
