### ISSUE TITLE
branch doesn't work

### ISSUE THREAD

**Issue by electricduck** [abiosoft/caddy-git#75]
I'm wanting to pull `release/live` from a repo I have (via a **webhook** on **Gogs**). It works fine the first time, however, every request to the webhook after that causes a 400 error (and fails to pull on the server). This does not occur if I use the main branch `develop`, but occurs on every other branch.

Here is my config:

```
git {
    repo https://{2FA-token}@git.zyr.io/zyrio/zyrbin
    path /var/lib/web/app/zyrbin
    hook /hooks/zyrbin/update-application {secret}
    interval -1
    branch release/live
    then /var/lib/web/build/zyrbin
}

```

**Comment by ivankolev** [comment]
@electricduck surround the branch name with double quotes. Probably the forward slash trips the parser. I've had similar problem with dot in the name, and I remembered somewhere in the docs a mention of the need to quote. Admittedly, the docs are sparse, but caddy is awesome 🥇
