### ISSUE TITLE
Webhook - Bad Request 400

### ISSUE THREAD

**Issue by derevandal** [abiosoft/caddy-git#78]
Hi, i'm trying to use github webhook but i recieve error 400.

Prints:
![screenshot_2](https://user-images.githubusercontent.com/1340508/30776603-00ccc086-a080-11e7-87f2-32a180cfe01f.png)
![screenshot_3](https://user-images.githubusercontent.com/1340508/30776604-00eb90d8-a080-11e7-943b-833db40226d8.png)
![screenshot_4](https://user-images.githubusercontent.com/1340508/30776605-00fca422-a080-11e7-9610-14a1ebacda61.png)

Caddyfile:
```
www.xxxx.com.br {
	tls xxx@xxxx.com.br
	root /var/www/html/
	fastcgi / /run/php/php7.1-fpm.sock php
	header / {
    		X-XSS-Protection "1; mode=block"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Strict-Transport-Security "max-age=15768000; includeSubdomains; preload;"
	}
  git git@github.com:derevandal/xxxx {
    key ~/.ssh/id_rsa
    path  xxxx/
    hook /webhook secret-password
    hook_type github
  }
	log /var/www/log/teste-access.log
	errors /var/www/log/teste-errors.log
	realip cloudflare
}
```

What did I wrong?

**Comment by rigon** [comment]
Same here... +1

**Comment by rigon** [comment]
Apparently, you need to configure **Content-type** to JSON.

**Comment by abiosoft** [comment]
@derevandal kindly confirm if setting the correct content-type fixed it.

**Comment by derevandal** [comment]
@rigon where can I configure? in caddy or in github?

**Comment by abiosoft** [comment]
On GitHub, webhook settings.

**Comment by derevandal** [comment]
Thanks. I got it.
![screenshot_4](https://user-images.githubusercontent.com/1340508/31051822-f814ca3c-a648-11e7-82fe-f6e5f8518dc4.png)

@abiosoft could you close?

**Comment by virtualdxs** [comment]
I'd like to ask that this be put in the documentation on the Caddy site.
