### ISSUE TITLE
Is it possible to specify a script to run instead of pulling?

### ISSUE THREAD

**Issue by griffins** [abiosoft/caddy-git#83]
Instead of pulling the latest commit id love to checkout the latest tag that has been pushed. I thought i could do a shell script script.

**Comment by abiosoft** [comment]
You can specify `{latest}` as the branch name to pull the latest tag as stated in docs https://caddyserver.com/docs/http.git.

You cannot run a custom command. What is possible at the moment is to run a command after a successful pull.

**Comment by griffins** [comment]
thanks, it will do the job for now
