### ISSUE TITLE
Problems Setting up gitlab hook

### ISSUE THREAD

**Issue by griffins** [abiosoft/caddy-git#84]
I used gitlab webhooks with caddy before but ive never tried using the {latest} flag for pulling latest tag.

When i trigger a tag push request nothing happens and a ```400 Bad request``` is sent back, when i trigger push request caddy logs ```gitlab webhook ignored. Error: found different branch master```

Here is my config 

``` 
git {
        repo git@gitlab.com:org/repo.git
        branch  {latest}
        key /path/to/key
        pull_args --all
        hook /webhook some_secret
        hook_type gitlab
        then_long /path/to/deploy.sh
        path ../
   }
````

Anywhere am going wrong?

**Comment by abiosoft** [comment]
This is weird. Let's try fixing by first trying with `master` branch.

**Comment by griffins** [comment]
Just noted when caddy starts everything works fine. Just that the webhooks don't work,
Anyways ill create a branch that points to the latest tag as a work around.
