### ISSUE TITLE
Update Setup function

### ISSUE THREAD

**Issue by mholt** [abiosoft/caddy-git#9]
Remember that nasty bug where git pull was being called twice concurrently, and they were conflicting with each other and causing the server to not start successfully? (Happened when a server block was associated with more than one host.) I fixed that in [0ac8bf5](https://github.com/mholt/caddy/commit/0ac8bf58ea7bc0d63b175e6de2c9cf5acbca7c86) by calling the Setup functions only once per server block, rather than once per host per server block.

Well this turned out to be problematic because then the Setup function didn't know which host it was setting up for which was, frankly, kinda dumb on my part. So I [reverted](https://github.com/mholt/caddy/commit/0c07f7adcce7deefd9b163c8c276b90a36af18b7) the change in a `configfix` branch so that Setup is called once per host per server block again. This way, like before, each time Setup is called, it's passed a server.Config that belongs to just that one host.

But now it has the possibility of executing your Startup callback more than once (the callback that executes the git pull command) and concurrently - like it did before. But now there are new fields on the Controller that you can use to do something just once per server block, namely the `OncePerServerBlock()` function :smile:

You can [use it like this](https://github.com/mholt/caddy/blob/691204ceed9fd2f3894f304adcaf3a80b511bb91/config/setup/startupshutdown.go#L58-L61):

```go
// the returned error is the error returned from the function you pass in
err := c.OncePerServerBlock(func() error {
    // this executes immediately as long as it hasn't
    // been executed for this server block yet
    return nil
})
```

So I would use this function to do your appending to the c.Startup or c.Shutdown slices, for example - or whatever you want to run only once per server block (i.e. once per appearance in the Caddyfile).

Let me know if you have any questions!

**Comment by abiosoft** [comment]
Nice. I'll refactor.

**Comment by abiosoft** [comment]
Fixed
