### ISSUE TITLE
RFE: whitelisted blocks of IP addresses for webhooks should be configurable

### ISSUE THREAD

**Issue by jumanjiman** [abiosoft/caddy-git#94]
## Current

Whitelisted IPs are hardcoded in the source, such as https://github.com/abiosoft/caddy-git/blob/1a565409d31651a957fdba74f964d86f249a8739/bitbucket_hook.go#L13-L19
This makes sense and is user-friendly for people who use BitBucket hosted.

## Request for enhancement

Add a config option `hook_ips` to allow a list of whitelisted IP blocks (single or CIDR block).
If the config option is not provided in config, the git plugin should use the default values (that are currently hardcoded). 

Example of proposed config:

```
git {
  repo  <some_uri>
  path  <some_path>
  hook /my_hook
  hook_type bitbucket

  # override the default IP whitelist
  hook_ips 192.168.0.0/24, 10.0.1.1
}
```

## Workaround

One current workaround for the requested behavior is to use `hook_type generic` since it does not have an IP whitelist.

**Comment by bilalakil** [comment]
Huge thanks for solving this 😀 👏 Works like magic now.
