### ISSUE TITLE
Error during parsing: Unknown directive 'repo'

### ISSUE THREAD

**Issue by DovaMerith** [abiosoft/caddy-git#95]
this is my config
```go
localhost:80 {
	root /home/bunny/www
}

git {
	repo     gitea@git.merith.tk:merith/caddy_site.git
	branch   master
	key      /home/bunny/.ssh/id_rsa
	path     /home/bunny/www
	interval 120
}
```
but when i run specifying the config file with ``caddy -conf /home/bunny/www/caddy.conf``, it spews this error
``/home/bunny/www/caddy.conf:6 - Error during parsing: Unknown directive 'repo'``
and this is the command i used to install caddy
``curl https://getcaddy.com | bash -s personal hook.service,http.filemanager,http.git
``

**Comment by abiosoft** [comment]
Your config is wrong. `git` should either be under the site or you can remove the braces from the site.

```
localhost:80
root /home/bunny/www

git {
	repo     gitea@git.merith.tk:merith/caddy_site.git
	branch   master
	key      /home/bunny/.ssh/id_rsa
	path     /home/bunny/www
	interval 120
}
```

**Comment by DovaMerith** [comment]
Yep, someone on Discord told me what I did wrong.
