### ISSUE TITLE
caddy-git error when cloning repos with custom port (SSH)

### ISSUE THREAD

**Issue by elg0ch0** [abiosoft/caddy-git#99]
Hi,

I'm getting this error

> fatal: repository 'git@git.mydomain.net/abcd/abc2.git' does not exist
> 2019/02/05 17:14:50 exit status 128
> exit status 128

when trying to clone my repo using caddy-git plugin, as shown in a snippet of my Caddyfile:

> ...
>      git {
>         repo    ssh://git@git.mydomain.net/abcd/abc2.git
>         path    /var/www/abcd/api
>         key     /var/www/abcd/.ssh/id_rsa
>         interval -1
>      }
> ...
>
and with a ~/.ssh/config like this:

> Host git.mydomain.net
>     HostName git.mydomain.net
>     Port 7999
>     User git
>     IdentityFile /var/www/mydomain/.ssh/id_rsa

  As a test I executed a
`git clone  ssh://git@git.mydomain.net/abcd/abc2.git /var/www/abcd/api
`
and it worked.

  This issue looks similar to those mentioned at [58](https://github.com/jumanjihouse/docker-caddy/pull/58), [69](https://github.com/abiosoft/caddy-git/issues/69) and [76](https://github.com/abiosoft/caddy-git/issues/76) but none of them indicate a solution.
 Is this a still existing issue? or is there a workaround/fix for it?

  Thanks,

**Comment by abiosoft** [comment]
Try `git@git.mydomain.net:abcd/abc2.git`

**Comment by werty1st** [comment]
My workaround is:
docker-compose:

    image: tecnativa/tcp-proxy
    environment:
      LISTEN: ":22"
      TALK: "git.bitbuket.corp:7999"
